// SPDX-FileCopyrightText: 2024 Softbear, Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum EntitySubKind {
    Battleship,
    Carrier,
    Corvette,
    Cruiser,
    Depositor,
    DepthCharge,
    Destroyer,
    Dreadnought,
    Dredger,
    Heli,
    Hovercraft,
    Icebreaker,
    Gun,
    Lcs,
    Mine,
    Minelayer,
    Missile,
    Mtb,
    Pirate,
    Plane,
    Ram,
    Rocket,
    RocketTorpedo,
    Sam,
    Score,
    Shell,
    Sonar,
    Structure,
    Submarine,
    Tanker,
    Torpedo,
    Tree,
}
