fmt:
	cargo fmt --manifest-path core_protocol/Cargo.toml
	cargo fmt --manifest-path common_util/Cargo.toml
	cargo fmt --manifest-path server_util/Cargo.toml
	cargo fmt --manifest-path game_server/Cargo.toml
	cargo fmt --manifest-path client_util/Cargo.toml
	cargo fmt --manifest-path engine_macros/Cargo.toml
	cargo fmt --manifest-path sprite_sheet/Cargo.toml
	cargo fmt --manifest-path sprite_sheet_util/Cargo.toml