name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: egor-tensin/setup-clang@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-10-28
        override: true
        components: rustfmt, clippy
    - name: Build Client
      working-directory: ./js
      run: npm install && npm run build
    - name: Build Server
      run: cargo build --release --manifest-path server/Cargo.toml --verbose
    - name: Upload Server
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: server/target/release/server
